[JobSearch]
site_name = [ "indeed", "linkedin", "glassdoor",]
search_term = ""
location = "hyderabad"
distance = 100
job_type = "parttime"
is_remote = true
results_wanted = 50
easy_apply = true
country_indeed = "india"
offset = 0
hours_old = 48
verbose = false
hyperlinks = true

[Resume]
resumeFilePath = "C:/jobs/uploads/Resume_29-05-24.pdf"

[GenAI]
openAIModel = "gpt-4"
